name: testing-updater

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test bosh-blob updater
    steps:
      - name: test
        run: |
          brew install aquasecurity/trivy/trivy
