name: testing-updater

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test bosh-blob updater
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02N3GGKXPB'  # Slack channel id or name to post message. https://api.slack.com/methods/chat.postMessage#channels
          slack-message: 'posting from a github action!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
