name: testing

on:
  push:
    branches:
      - main
      
jobs:
  check-for-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "vmware-tanzu/carvel-kapp"
          latest: true
          fileName: "*"
      - name: check-files
        run: |
          ls -la
