name: testing

on:
  schedule:
    - cron: '* * * * *'

jobs:
  check-for-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "neil-hickey/actions-testing"
          latest: true
          fileName: "*"
      - check-files:
        run: |
          ls -la
