name: testing

on:
  push:
    branches:
      - main
      
jobs:
  check-for-releases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: ['ytt', 'kapp']
    steps:
      - name: check-latest-release
        env:
          tool: ${{ matrix.tool }}
        run: |
          curl -sL https://api.github.com/repos/vmware-tanzu/carvel-${{ tool }}/releases/latest | jq -r '.tag_name'
