name: testing

on:
  push:
    tags:
      - 'v*'
      
jobs:
  check-for-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Current Release Version
        run: |
        
          VERSION=${{ github.event.release.tag_name }}
          
          cat << EOF > pkgi.yml
          ---
          apiVersion: packaging.carvel.dev/v1alpha1
          kind: PackageInstall
          metadata:
            name: secretgen-controller
          spec:
            serviceAccountName: cluster-admin-sa
            packageRef:
              refName: secretgen-controller.carvel.dev
              apiVersion: packaging.carvel.dev/v1alpha1
              versionSelection:
                constraints: "${VERSION:1}"
          EOF
          
          cat pkgi.yml
